### ISSUE TITLE
Kitten starts to flicker when turn off frustum culling and lod together 

### ISSUE THREAD

**Issue by jsjtxietian** [zeux/niagara#36]
When I press C to turn off frustum culling and then press L to disable lod ,  the screen start to flickering as the video shows. If disable either frustum culling or lod, it will be stable again.

https://github.com/zeux/niagara/assets/8315986/018056fb-1af2-457b-bd8b-871c4252e0ac

**Comment by zeux** [comment]
Thanks - yeah I noticed this before but didn't act on it. Some fixed limit somewhere is probably being exhausted, will take a look.

**Comment by jsjtxietian** [comment]
>  Some fixed limit somewhere is probably being exhausted.

After some investigation I found the bug was probaly introduced by this commit https://github.com/zeux/niagara/commit/0eae88480ad110d5ecabed74b4452ab6d7136881

**Comment by zeux** [comment]
Yeah, with task command submission and all culling/LOD disabled we need ~80M commands (each command will submit ~4K triangles), for a total of ~320B triangles/frame.

The buffer we allocate for commands is enough for ~6.7M, and the encoding in `tasksubmit.comp.glsl` restricts it further to ~4M. The flickering is due to variability in GPU scheduling for writes to the task list which results in different geometry rendered per frame as the list isn't constructed in deterministic order.

**Comment by zeux** [comment]
Ah, right, and part of the issue is that this is a fundamental limitation of `EXT_mesh_shader` as `maxTaskWorkGroupTotalCount` is only guaranteed to be 4M (and is actually 4M on NV driver). So this isn't really avoidable in a meaningful sense with the approach of using a single draw call - multiple draw calls work but we had to stop doing that to avoid inefficiencies in GPU submission on AMD hardware.

It looks like we should do some code cleanup around this, eg to avoid buffer overrun and overallocation (we currently reserve 128 MB for draw commands, and yet the maximum amount of memory 4M commands use is ~80MB), but fundamentally it feels like a limitation that is fine to keep, as drawing more than 32B triangles in a single scene is impractical for performance.

**Comment by jsjtxietian** [comment]
Thank you for the explanation and clarification！
